name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        # with:
        #   version: 0.1.0
      
      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Release
        run: bun publish
        working-directory: core
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Github Release
        # uses: softprops/action-gh-release@v1
        # with:
        #   files: |
        #     core/dist/*
        #   token: ${{ secrets.GITHUB_TOKEN }}

